version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      - DEBUG=app:error,app:warn,app:info,app:log:*
    ports:
      - "8082:8082"
    volumes:
      - .:/graph   
volumes:
  db_data:
    driver: local